#!/bin/bash

# Basic shell info
# Check what shell you're using and its version
echo $SHELL
bash --version

#  Navigation commands
pwd              # Show current directory
cd               # Go to home directory
cd ~             # Same as above
cd ..            # Move up one level
cd /             # Go to root directory

#  Listing files and folders
ls               # List contents
ls -l            # Long listing
ls -a            # Show hidden files
ls -la           # Combined

#  File and folder operations
mkdir testfolder            # Create a folder
touch file1.txt             # Create a file
cp file1.txt file2.txt      # Copy file
mv file2.txt renamed.txt    # Rename/move file
rm file1.txt                # Remove file
rm -r testfolder            # Delete folder recursively

#  Home directory usage
cd ~            # Go to home
echo ~          # Print home path
cd ~/Documents  # Go to Documents

# Wildcards
ls *.txt         # All .txt files
ls file?.txt     # One-character wildcard
ls file[1-3].txt # Range pattern match

#  Brace Expansion
echo file{1,2,3}.txt      # file1.txt file2.txt file3.txt
echo {a..e}               # a b c d e
echo {1..5}               # 1 2 3 4 5
touch file{1..5}.txt      # Create 5 files

#  Input/Output Redirection
echo "Hello" > output.txt       # Overwrite file
cat < output.txt                # Read from file
echo "Appended" >> output.txt   # Append
cat output.txt                  # Display content

#  Pipes
cat output.txt | sort | more          # Chain output to sort to more
cut -d: -f1 /etc/passwd | sort        # Cut usernames and sort

#  Background jobs
sleep 10 &     # Run command in background
jobs           # Check background jobs
fg             # Bring last job to foreground

#  Special Characters & Quoting
name="Shiva"
echo "Hello $name"         # Double quotes allow substitution
echo '$name'              # Single quotes prevent substitution
echo "Today is $(date)"   # Command substitution
echo Hello\!              # Escaped character

#  Clean up practice files
rm file{1..5}.txt
rm output.txt
rm renamed.txt
